### ISSUE TITLE
Need a way to toggle between selected or unselected programmatically without user interaction

### ISSUE THREAD

**Issue by kkbear1985** [NikhilVadoliya/FlutterAnimatedButton#2]
**Is your feature request related to a problem? Please describe.**
need it to implement a feature such that only 1 of multiple animated button is selected

**Describe the solution you'd like**
either expose the selected state by widget key or provide a toggle function for calling

**Comment by nikhil-concetto** [comment]
Hey @kkbear1985 , Thank for your suggestion. I will add one parameter in Widget.

**Comment by NikhilVadoliya** [comment]
Hey @kkbear1985 , I have implement this enhancement in plugin and upload it. please update package version

**Comment by kkbear1985** [comment]
work perfectly, thanks very much

**Comment by marc-walton** [comment]
> @NikhilVadoliya work perfectly, thanks very much

How did you do it? I used isSelected but I don't know how to implement select only one like shown in the  app screenshot in readme in pub. dev

**Comment by marc-walton** [comment]
> Hey @kkbear1985 , I have implement this enhancement in plugin and upload it. please update package version

How did you do it? I used isSelected but I don't know how to implement select only one like shown in the  app screenshot in readme in pub. dev

**Comment by NikhilVadoliya** [comment]
Hey @marc-walton , Let go with 4 button with single selection

- First you need to create four bool variable `isSelected1`, `isSelected2`, `isSelected3` and `isSelected4` and assign to each animatedButton. 
- Now, when user press on button1 then call setState method with set other three variable **`false`** ( `isSelected2`, `isSelected3` and `isSelected4`) and  `isSelected1` is **`true`**. 
- Same do for other three button on press
