### ISSUE TITLE
Feature to automatically expand with respect to give text.

### ISSUE THREAD

**Issue by arpit24sahu** [NikhilVadoliya/FlutterAnimatedButton#5]
When I try to enter a very long text in the button, it fails to expand itself (like a container), and will show only the first line. Setting the height to some greater value won't help here as the string was coming from an API, and predicting the number of lines a string will acquire is not possible.

**Comment by NikhilVadoliya** [comment]
Can you please share video and your sample code ?

**Comment by arpit24sahu** [comment]
Hi,
I have attached a sample code and the video depicting what I want to achieve.
Thanls

https://user-images.githubusercontent.com/66864322/118441255-8ee52200-b706-11eb-9a0a-6ad2d379eca1.mp4


[code.txt](https://github.com/NikhilVadoliya/FlutterAnimatedButton/files/6491570/code.txt)

**Comment by NikhilVadoliya** [comment]
Hello @arpit24sahu , We will manage this type of scenario in future meanwhile you can use button width and height
