### ISSUE TITLE
An Extra animation and an on hover animation.

### ISSUE THREAD

**Issue by AlyElashram** [NikhilVadoliya/FlutterAnimatedButton#7]
This library is amazing however I feel like that an on hover animation is missing from flutter in general and given that this library can easily add that it would be amazing. The on hover animation should start whenever the mouse is on the button and then reverse when the mouse is removed from the button. The second feature would be to animate the borders of the button on click or on hover. meaning that the border gets drawn either from bottom to top or from the corner to the opposite corner .

**Comment by nikhil-concetto** [comment]
Hello @AlyElashram , Thanks you feedback

Animation `onHover` feature added in version `2.0.1` and other animation will added in future.
